#!/bin/bash

# Move xorg cache files
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# Run system config files
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


numlockx
xrdb "$XDG_CONFIG_HOME"/X11/Xresources
eval $(xrdb-env)
[ "$HOSTNAME" = "DESKTOP-MADS" ] && kdeconnectd &
[ "$HOSTNAME" = "DESKTOP-MADS" ] && caffeine &
wp &
dunst &
[ "$HOSTNAME" = "laptop-mads" ] && picom -b
exec i3
