#!/bin/sh

BAT_NUMBER=${BAT_NUMBER:-1}
LABEL=${LABEL:-""}
FULL_LABEL=${FULL_LABEL:-"⚡"}
DISC_LABEL=${DISC_LABEL:-"🔋"}
CHAR_LABEL=${CHAR_LABEL:-"🔌"}
NCHA_LABEL=${NCHA_LABEL:-"🛑"}
UNKN_LABEL=${UNKN_LABEL:-"♻️"}
LOWB_LABEL=${LOWB_LABEL:-"❗"}


battery="/sys/class/power_supply/BAT$BAT_NUMBER"

[ -d "$battery" ] || exit 0


bat_status=$(cat "$battery/status")
bat_capacity=$(cat "$battery/capacity")

case "$bat_status" in
  "Full")         bat_status="$FULL_LABEL" ;;
  "Discharging")  bat_status="$DISC_LABEL" ;;
  "Charging")     bat_status="$CHAR_LABEL" ;;
  "Not charging") bat_status="$NCHA_LABEL" ;;
  "Unknown")      bat_status="$UNKN_LABEL" ;;
esac

bat_color="$XRDB_FOREGROUND"

[ "$bat_capacity" -lt "25" ] && bat_color="$XRDB_COLOR1"
[ "$bat_capacity" -lt "25" ] && [ "$bat_status" = "$DISC_LABEL" ] && bat_status="$LOWB_LABEL"

echo "$LABEL$bat_status$bat_capacity%"
echo "$LABEL$bat_status$bat_capacity%"
echo "$bat_color"
