#!/bin/sh

case "$1" in
  "left" ) wmctrl -l -G | awk '$2 != -1 && $3 < 1920 {print $1, $3 + 1920, $4}' | xargs -L1 xdotool windowmove ;;
  "right" ) wmctrl -l -G | awk '$2 != -1 && $3 >= 3840 {print $1, $3 - 1920, $4}' | xargs -L1 xdotool windowmove ;;
  "all" ) wr left; wr right;;
  *) echo "Invalid argument" >&2 ;;
esac
