# This is a basic workflow to help you get started with Actions

name: CI (shellcheck)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  shellcheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: ShellCheck
      uses: ludeeus/action-shellcheck@0.5.0
      with:
        # Paths to ignore when running ShellCheck
        ignore: .config/,.local/
        # Minimum severity of errors to consider. Options: [error, warning, info, style]
        severity: style
        # Run shellcheck on _all_ files at once, instead of one at a time
        check_together: 'no'
